
file6 = open('name.txt')
print('当前文件指针的位置 %s' % file6.tell())
print('当前读取到了一个字符内容是 %s' % file6.read(1))
print('当前文件指针的位置 %s' % file6.tell())
file6.seek(5, 0)
print('我们进行seek操作')
print('当前文件指针的位置 %s' % file6.tell())
print('当前读取到了一个字符内容是 %s' % file6.read(1))
print('当前文件指针的位置 %s' % file6.tell())
file6.close()
